name: Deploy to Server via SFTP (SSH)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: SFTP Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      - name: 📤 SFTP Upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # O usar password
          password: ${{ secrets.SFTP_PASSWORD }}  # Si usas contraseña en lugar de llave SSH
          port: 22
          local_path: './*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}  # Ruta en el servidor
          sftp_only: true
          delete_remote_files: false  # No borrar archivos remotos que no están en Git

      - name: ✅ Deployment Success
        run: |
          echo "✅ Deployment completed!"
          echo "🌐 Application deployed to ticket.ieeetadeo.org"
